name: "New tag"
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}

  publish-prod-tag:
    needs: tests
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: production
      oauth-redirect-url: https://heracles.app.radix.equinor.com
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}

  set-tag-ref:
    runs-on: ubuntu-latest
    outputs:
      tag-ref: ${{ steps.tag-ref.outputs.tag-ref }}
      oauth-redirect-url: https://heracles.app.radix.equinor.com
    steps:
      - uses: actions/checkout@master
      - id: create-ref
        run: |
          TAG_REF=$(echo $GITHUB_REF | cut -d / -f 3)
          echo "::set-output name=tag-ref::TAG_REF"

  publish-tag-ref:
    needs: [set-tag-ref, tests]
    uses: ./.github/workflows/publish.yaml
    with:
      image-tag: ${{ needs.set-tag-ref.outputs.tag-ref }}
      oauth-redirect-url: https://heracles.app.radix.equinor.com
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}

  deploy:
    needs: publish-prod-tag
    uses: ./.github/workflows/deploy.yaml
    with:
      radix-environment: 'prod'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
