name: Generate documentation

on:
  # Workflow dispatch is used for manual triggers
  workflow_dispatch:
    inputs:
      message:
        description: 'A message to shown in the changelog'
        default: ''
        required: false
        type: string
  # Workflow call is used for called from another workflow
  workflow_call:
    inputs:
      message:
        description: 'A message to shown in the changelog'
        default: ''
        required: false
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main

    - name: 'Setup node'
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: documentation/yarn.lock

    - name: Download CHANGELOG
      uses: actions/download-artifact@v3
      with:
        name: CHANGELOG

    - name: 'Add changelog'
      shell: bash
      run: |
        sed -i -e '1i${{ inputs.message }}\' CHANGELOG.md
        cp CHANGELOG.md documentation/src/pages/changelog.md
    
    - name: Install dependencies and build website
      run: |
        cd documentation
        yarn install --frozen-lockfile
        yarn build

    - name: GitHub Pages
      # if: github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: documentation/build/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
