name: "Publish container images"
on:
  workflow_dispatch:
  workflow_call:  # Workflow is meant to be called from another workflow, with the image tag as input
    inputs:
      image-tag:
        description: 'Which tag to set for the produced docker images'
        default: 'latest'
        required: true
        type: string
      oauth-redirect-url:
        description: 'redirect url for oauth. Should be the public url to access the web app'
        default: 'https://data-modelling-tool.app.radix.equinor.com'
        required: true
        type: string
    secrets:
      ACR_SECRET:
        required: false


env:
  IMAGE_REGISTRY: heracles.azurecr.io
  REGISTRY_USER: heracles
  API_IMAGE: heracles.azurecr.io/dmt/api
  WEB_IMAGE: heracles.azurecr.io/dmt/web
  SRS_IMAGE: heracles.azurecr.io/dmt-job/srs

jobs:
  build-and-publish-web-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build and Publish Web"
        run: |
          echo "Tagging with ${{ inputs.image-tag }}"
          docker login -u $REGISTRY_USER -p ${{ secrets.ACR_SECRET }} $IMAGE_REGISTRY
          docker pull $WEB_IMAGE
          echo $(git log -n 1 --format=format:'%h% %>(12) %cs %>(12,mtrunc)%aN%  %s %D') > ./web/packages/home/public/version.txt
          docker build \
          --build-arg REDIRECT_URI=${{inputs.oauth-redirect-url}} \
          --build-arg AUTH_ENABLED=1 \
          --build-arg AUTH_SCOPE=api://97a6b5bd-63fb-42c6-bb75-7e5de2394ba0/dmss \
          --build-arg CLIENT_ID=97a6b5bd-63fb-42c6-bb75-7e5de2394ba0 \
          --build-arg TENANT_ID=3aa4a235-b6e2-48d5-9195-7fcf05b459b0 \
          --cache-from ${WEB_IMAGE} \
          --tag ${WEB_IMAGE} \
          ./web
          docker tag $WEB_IMAGE $WEB_IMAGE:${{ inputs.image-tag }}
          docker push $WEB_IMAGE:${{ inputs.image-tag }}

  build-and-publish-api-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build and Publish API"
        run: |
          echo "Tagging with ${{ inputs.image-tag }}"
          docker login -u $REGISTRY_USER -p ${{ secrets.ACR_SECRET }} $IMAGE_REGISTRY
          docker pull $API_IMAGE
          echo $(git log -n 1 --format=format:'%h% %>(12) %cs %>(12,mtrunc)%aN%  %s %D') > ./api/src/version.txt
          docker build --cache-from $API_IMAGE --target prod --tag $API_IMAGE ./api
          docker tag $API_IMAGE $API_IMAGE:${{ inputs.image-tag }}
          docker push $API_IMAGE:${{ inputs.image-tag }}
